# libraries & global vars

In [1]:
import pandas as pd

# import combined leaders

In [2]:
## combined leaders to clean - file in
file_9999_leaders_toclean = "../../data/combined data/combined data - 1 cleaning/leaders_toparse.csv"
merged_leaders = pd.read_csv(file_9999_leaders_toclean,dtype="str")

In [3]:
# merged_leaders

,LeaderID,Name,Sex,BirthYear,BirthCountry,BirthCP,BirthBCC,DeathReported,MOUID_2015,KoreanName_2015,Name_2022,NameAlternative_2022,BirthString_2015,BirthDateString_2022,BirthPlaceString_2022,DeathString_2015,DeathString_2022
0,강관주,강관주,남성,1930,한반도,평남,대동군,NaN,807,강관주,강관주,NaN,1930.7.5 평남 대동군,1930년 07월 05일,평안남도 대동군,NaN,연도미상
1,강능수,강능수,남성,1930,한반도,평양,NaN,(사망),430,강능수,강능수,NaN,1930.2.21 평양,1930년 02월 21일,평양시,NaN,2015년 07월 01일
2,강동윤,강동윤,남성,NaN,NaN,NaN,NaN,NaN,153,강동윤,강동윤,NaN,NaN,연도미상,NaN,NaN,연도미상
3,강련학,강련학,남성,1932,NaN,NaN,NaN,(사망),542,강련학,강련학,강연학,1932년생,연도미상,NaN,NaN,2016년 10월 01일
4,강명철,강명철,남성,NaN,NaN,NaN,NaN,NaN,NaN,NaN,강명철,NaN,NaN,연도미상,NaN,NaN,연도미상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
663,오광철,오광철,NaN,1959,NaN,NaN,NaN,NaN,705,오광철,NaN,NaN,1959.6.15,NaN,NaN,NaN,NaN
664,오길방,오길방,NaN,1936,NaN,NaN,NaN,NaN,706,오길방,NaN,NaN,1936년생,NaN,NaN,NaN,NaN
665,우두태,우두태,NaN,1940,한반도,강원,고성,NaN,707,우두태,NaN,NaN,"1940년생, 강원 고성",NaN,NaN,NaN,NaN
666,이공필,이공필,NaN,NaN,NaN,NaN,NaN,NaN,709,이공필,NaN,NaN,NaN,NaN,NaN,NaN,NaN
667,이금범,이금범,NaN,1941,NaN,NaN,NaN,NaN,711,이금범,NaN,NaN,1941.1.3,NaN,NaN,NaN,NaN

# import and merge 2015 & 2022 career tables

In [6]:
## 2022 career - table - file in
file_2022_career_table = "../../data/2022 data/2022 data - 2 tables/career_everything.csv"
new_career = pd.read_csv(file_2022_career_table,dtype="str")
new_career.columns = [item+"_2022" if item != "LeaderID" else item for item in list(new_career.columns)]

In [7]:
## 2015 career - raw - file in
file_2015_career_raw = "../../data/2015 data/2015 data - 0 raw/leaderschoollinkmou.csv"
old_career_columns = ["MOUID_2015", "Name", "CareerStringID_2015", "CareerString_2015", "CareerStartYear", "CareerStartMonth", "EventType", "JointAppointment", "Org1", "Org2", "Org3", "Org4", "Org5", "Position", "OrgLevel", "PositionLevel", "OrgPositionString"]
old_career = pd.read_csv(file_2015_career_raw,sep=";",dtype="str",names=old_career_columns)

In [10]:
## combined career - cleaning - file out
file_9999_career_cleaning = "../../data/combined data/combined data - 1 cleaning/career_everything_toparse.csv"

In [11]:
# add LeaderID to old_family. select columns to merge with new_family
merged_leaders_key = merged_leaders[["LeaderID","MOUID_2015"]]
old_career_withid = old_career.merge(merged_leaders_key,on="MOUID_2015",how="inner")
#old_education_withid = old_education_withid[["LeaderID","FamilyString_2015"]]

In [12]:
merged_career = new_career.merge(old_career_withid,on="LeaderID",how="outer")

In [14]:
merged_career

,LeaderID,CareerDateString_2022,CareerString_2022,MOUID_2015,Name,CareerStringID_2015,CareerString_2015,CareerStartYear,CareerStartMonth,EventType,JointAppointment,Org1,Org2,Org3,Org4,Org5,Position,OrgLevel,PositionLevel,OrgPositionString
0,강관주,2011.12,김정일 국가장의위원회 위원,807,강관주,1960. 김일성종합대학 역사학부 졸업,1960,김일성종합대학교,대학교,북한,1960_김일성종합대학교_대학교_북한,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,강관주,2011.12,김정일 국가장의위원회 위원,807,강관주,연도미상김일성고급당학교 졸업,NaN,김일성고급당학교,특수학교,북한,year_김일성고급당학교_특수학교_북한,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,강관주,2010.09,조선노동당 중앙위원회 후보위원,807,강관주,1960. 김일성종합대학 역사학부 졸업,1960,김일성종합대학교,대학교,북한,1960_김일성종합대학교_대학교_북한,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,강관주,2010.09,조선노동당 중앙위원회 후보위원,807,강관주,연도미상김일성고급당학교 졸업,NaN,김일성고급당학교,특수학교,북한,year_김일성고급당학교_특수학교_북한,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,강관주,2010.04,김중린 국가장의위원회 위원,807,강관주,1960. 김일성종합대학 역사학부 졸업,1960,김일성종합대학교,대학교,북한,1960_김일성종합대학교_대학교_북한,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9874,송석환,NaN,NaN,701,송석환,연도미상 평양음악대학,NaN,평양음악대학교,대학교,북한,year_평양음악대학교_대학교_북한,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9875,오광철,NaN,NaN,705,오광철,연도미상 김일성종합대 프랑스어과 졸업,NaN,김일성종합대학교,대학교,북한,year_김일성종합대학교_대학교_북한,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9876,오길방,NaN,NaN,706,오길방,연도미상 김일성종합대학 졸업,NaN,김일성종합대학교,대학교,북한,year_김일성종합대학교_대학교_북한,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9877,우두태,NaN,NaN,707,우두태,연도미상 문평제련소 공장대학 야금과,NaN,공장대학,대학교,북한,year_공장대학_대학교_북한,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9878,이금범,NaN,NaN,711,이금범,연도미상 평양체신대학 전자공학,NaN,평양체신대학교,대학교,북한,year_평양체신대학교_대학교_북한,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
# career in 2015, but not 2022 - X rows
# merged_education[merged_education.EducationDateString_2022.isnull() & merged_education.EducationString_2015.notnull()]

In [31]:
# career in 2022, but not 2015 - X rows
# merged_education[merged_education.EducationDateString_2022.notnull() & merged_education.EducationString_2015.isnull()]

In [33]:
# career overlap in 2015 & 2022 - X rows
# merged_education[merged_education.EducationDateString_2022.notnull() & merged_education.EducationString_2015.notnull()]

In [38]:
# all null - X rows - can delete these
# merged_education[merged_education.EducationDateString_2022.isnull() & merged_education.EducationString_2015.isnull()]

# export combined education - to cleaning

In [15]:
# export to combined education - to cleaning
merged_career.to_csv(file_9999_career_cleaning,index=False)