In [1]:
import pandas as pd
#pd.set_option('display.max_rows', None)

In [2]:
# https://nkinfo.unikorea.go.kr/nkp/theme/peopleList.do

nklist = pd.read_excel("../new data/NK elite new checklist.xlsx")
nklist

,Leader ID,Name,성명(한글),소속/직책,성별,생년월일,출생지,사망여부,사망일자
0,강관주,강관주,NaN,NaN,남성,1930년 07월 05일,평안남도 대동군,NaN,연도미상
1,강능수,강능수,NaN,(사망) 당 중앙위원회 위원,남성,1930년 02월 21일,평양시,(사망),2015년 07월 01일
2,강동윤,강동윤,NaN,당 중앙위원회 부부장,남성,연도미상,NaN,NaN,연도미상
3,강련학,강련학,강연학,(사망) 민족화해협의회 부회장,남성,연도미상,NaN,(사망),2016년 10월 01일
4,강명철,강명철,NaN,조선그리스도교연맹 중앙위원회 위원장,남성,연도미상,NaN,NaN,연도미상
...,...,...,...,...,...,...,...,...,...
600,황병서,황병서,NaN,인민군 차수,남성,1949년,NaN,NaN,연도미상
601,황봉영,황봉영,NaN,조선올림픽위원회 부위원장,남성,1944년 08월 15일,NaN,NaN,연도미상
602,황순희,황순희,NaN,(사망) 조선혁명박물관 관장,여성,1919년 05월 03일,북한지역외 중국,(사망),2020년 01월 17일
603,황철식,황철식,NaN,NaN,미상,연도미상,NaN,NaN,연도미상
604,황학원,황학원,NaN,NaN,남성,1941년 01월 01일,NaN,NaN,연도미상

In [3]:
nklist.columns

Index(['Leader ID', 'Name', '성명(한글)', '소속/직책', '성별', '생년월일', '출생지', '사망여부',
       '사망일자'],
      dtype='object')

In [4]:
nklist=nklist.rename(columns={"Leader ID":"ID"})

In [5]:
nklist

,ID,Name,성명(한글),소속/직책,성별,생년월일,출생지,사망여부,사망일자
0,강관주,강관주,NaN,NaN,남성,1930년 07월 05일,평안남도 대동군,NaN,연도미상
1,강능수,강능수,NaN,(사망) 당 중앙위원회 위원,남성,1930년 02월 21일,평양시,(사망),2015년 07월 01일
2,강동윤,강동윤,NaN,당 중앙위원회 부부장,남성,연도미상,NaN,NaN,연도미상
3,강련학,강련학,강연학,(사망) 민족화해협의회 부회장,남성,연도미상,NaN,(사망),2016년 10월 01일
4,강명철,강명철,NaN,조선그리스도교연맹 중앙위원회 위원장,남성,연도미상,NaN,NaN,연도미상
...,...,...,...,...,...,...,...,...,...
600,황병서,황병서,NaN,인민군 차수,남성,1949년,NaN,NaN,연도미상
601,황봉영,황봉영,NaN,조선올림픽위원회 부위원장,남성,1944년 08월 15일,NaN,NaN,연도미상
602,황순희,황순희,NaN,(사망) 조선혁명박물관 관장,여성,1919년 05월 03일,북한지역외 중국,(사망),2020년 01월 17일
603,황철식,황철식,NaN,NaN,미상,연도미상,NaN,NaN,연도미상
604,황학원,황학원,NaN,NaN,남성,1941년 01월 01일,NaN,NaN,연도미상

In [7]:
nklist[nklist["ID"].str.contains("a")]

,ID,Name,성명(한글),소속/직책,성별,생년월일,출생지,사망여부,사망일자
47,김경호a,김경호,NaN,조선태권도위원회 국제태권도연맹 부총재,남성,1958년 12월 11일,강원도,NaN,연도미상
53,김광철a,김광철,NaN,NaN,남성,연도미상,NaN,NaN,연도미상
57,김금철a,김금철,NaN,NaN,남성,연도미상,NaN,NaN,연도미상
72,김명길a,김명길,NaN,외무성 대사,남성,1959년 03월 14일,자강도 만포시,NaN,연도미상
110,김영일a,김영일,NaN,조선.일본우호친선협회 고문,남성,1947년 03월 17일,평안북도 정주시,NaN,연도미상
114,김영철a,김영철,NaN,당 통일전선부 부장,남성,1946년,량강도,NaN,연도미상
119,김영훈a,김영훈,NaN,NaN,미상,연도미상,NaN,NaN,연도미상
136,김윤혁a,김윤혁,NaN,(사망),남성,1926년,평안남도 양덕군,(사망),2006년 04월
144,김일철a,김일철,NaN,NaN,남성,1930년,평양시,NaN,연도미상
193,김형식a,김형식,NaN,NaN,남성,연도미상,NaN,NaN,연도미상
245,리성국a,리성국,NaN,(사망),남성,연도미상,NaN,(사망),연도미상
260,리용철a,리용철,이용철,(사망),남성,1929년 03월 24일,NaN,(사망),2010년 04월
329,박명철a,박명철,NaN,조국통일민주주의전선 의장,남성,1941년 09월 15일,평양시,NaN,연도미상
332,박성철a,박성철,NaN,(사망) 최고인민회의 상임위원회 명예부위원장,남성,1913년 09월 02일,북한지역외 남한 경북 경주,(사망),2009년 10월 29일
551,최영호a,최영호,NaN,인민군 상장,남성,연도미상,NaN,NaN,연도미상

In [8]:
nklist[nklist["ID"].duplicated()]

Empty DataFrame
Columns: [ID, Name, 성명(한글), 소속/직책, 성별, 생년월일, 출생지, 사망여부, 사망일자]
Index: []

In [9]:
import os
os.listdir()

['.ipynb_checkpoints',
 '1_compare elites in folder an list.ipynb',
 '2_compare old and new elite names.ipynb',
 '3_extract uncoded career strings from old data.ipynb',
 'Checklist.docx']

In [11]:
fn=os.listdir('../new data/NK elite spreadsheets/')

In [12]:
fn

['강관주 상세정보.xls',
 '강능수 상세정보.xls',
 '강동윤 상세정보.xls',
 '강련학 상세정보.xls',
 '강명철 상세정보.xls',
 '강민철 상세정보.xls',
 '강봉훈 상세정보.xls',
 '강석숭 상세정보.xls',
 '강석주 상세정보.xls',
 '강성산 상세정보.xls',
 '강수린 상세정보.xls',
 '강순남 상세정보.xls',
 '강양모 상세정보.xls',
 '강영섭 상세정보.xls',
 '강영수 상세정보.xls',
 '강영철 상세정보.xls',
 '강영호 상세정보.xls',
 '강윤석 상세정보.xls',
 '강종관 상세정보.xls',
 '강지영 상세정보.xls',
 '강창욱 상세정보.xls',
 '강표영 상세정보.xls',
 '강하국 상세정보.xls',
 '강형봉 상세정보.xls',
 '계명철 상세정보.xls',
 '계영삼 상세정보.xls',
 '계응태 상세정보.xls',
 '고길선 상세정보.xls',
 '고인호 상세정보.xls',
 '고정범 상세정보.xls',
 '고종덕 상세정보.xls',
 '고철만 상세정보.xls',
 '곽범기 상세정보.xls',
 '곽창식 상세정보.xls',
 '구본태 상세정보.xls',
 '궁석웅 상세정보.xls',
 '권성호 상세정보.xls',
 '권영진 상세정보.xls',
 '권춘학 상세정보.xls',
 '권혁봉 상세정보.xls',
 '권호웅 상세정보.xls',
 '권희경 상세정보.xls',
 '기광호 상세정보.xls',
 '김격식 상세정보.xls',
 '김경남 상세정보.xls',
 '김경옥 상세정보.xls',
 '김경준 상세정보.xls',
 '김경호a 상세정보.xls',
 '김경호b 상세정보 .xlsx',
 '김경희 상세정보.xls',
 '김계관 상세정보.xls',
 '김광린 상세정보.xls',
 '김광영 상세정보.xls',
 '김광철a 상세정보.xls',
 '김광철b 상세정보.xls',
 '김광혁 상세정보.xls',
 '김국태 상세정보.xls',
 '김금철a 상세정보.xls',
 '김금철b 상세정보.xls',
 '김기남 상세정보.xls',
 '김기룡 상세정보.xls',
 '김능오 상세정보.xls',
 '김덕훈 상세정보.xls',
 '김동선 상세정보.xls',
 '김두일 상세정보.xls',
 '김락겸 상세정보.xls',
 '김락희 상세정보.xls',
 '김령성 상세정보.xls',
 '김류호 상세정보.xls',
 '김만성 상세정보.xls',
 '김만수 상세정보.xls',
 '김명국 상세정보.xls',
 '김명길a 상세정보.xls',
 '김명길b 상세정보.xls',
 '김명남 상세정보.xls',
 '김명식 상세정보.xls',
 '김명철 상세정보.xls',
 '김명훈 상세정보.xls',
 '김병률 상세정보.xls',
 '김병팔 상세정보.xls',
 '김병호 상세정보.xls',
 '김병훈 상세정보.xls',
 '김봉영 상세정보.xls',
 '김봉철 상세정보.xls',
 '김석준 상세정보.xls',
 '김성 상세정보.xls',
 '김성규 상세정보.xls',
 '김성기 상세정보.xls',
 '김성남 상세정보.xls',
 '김성룡 상세정보.xls',
 '김성애 상세정보.xls',
 '김성일 상세정보.xls',
 '김성준 상세정보.xls',
 '김성혜 상세정보.xls',
 '김성호 상세정보.xls',
 '김세복 상세정보.xls',
 '김송철 상세정보.xls',
 '김수길 상세정보.xls',
 '김수열 상세정보.xls',
 '김승두 상세정보.xls',
 '김승찬 상세정보.xls',
 '김시학 상세정보.xls',
 '김양건 상세정보.xls',
 '김양점 상세정보.xls',
 '김여정 상세정보.xls',
 '김영남 상세정보.xls',
 '김영녀 상세정보.xls',
 '김영대 상세정보.xls',
 '김영숙 상세정보.xls',
 '김영식 상세정보.xls',
 '김영일a 상세정보.xls',
 '김영일b 상세정보 .xls',
 '김영재 상세정보.xls',
 '김영주 상세정보.xls',
 '김영철a 상세정보.xls',
 '김영철b 상세정보.xls',
 '김영춘 상세정보.xls',
 '김영호 상세정보.xls',
 '김영환 상세정보.xls',
 '김영훈a 상세정보.xls',
 '김영훈b 상세정보.xls',
 '김완수 상세정보.xls',
 '김용걸 상세정보.xls',
 '김용광 상세정보.xls',
 '김용선 상세정보.xls',
 '김용수 상세정보.xls',
 '김용순 상세정보.xls',
 '김용연 상세정보.xls',
 '김용주 상세정보.xls',
 '김용진 상세정보.xls',
 '김용철 상세정보.xls',
 '김웅철 상세정보.xls',
 '김원균 상세정보.xls',
 '김원홍 상세정보.xls',
 '김유일 상세정보.xls',
 '김윤심 상세정보.xls',
 '김윤혁a 상세정보.xls',
 '김윤혁b 상세정보.xls',
 '김의순 상세정보.xls',
 '김익현 상세정보.xls',
 '김인식 상세정보.xls',
 '김일 상세정보.xls',
 '김일국 상세정보.xls',
 '김일성 상세정보.xls',
 '김일철a 상세정보.xls',
 '김일철b 상세정보.xls',
 '김재룡 상세정보.xls',
 '김재성 상세정보.xls',
 '김정각 상세정보.xls',
 '김정관 상세정보.xls',
 '김정기 상세정보.xls',
 '김정남 상세정보.xls',
 '김정숙 상세정보.xls',
 '김정순 상세정보.xls',
 '김정식 상세정보.xls',
 '김정은 상세정보.xls',
 '김정일 상세정보.xls',
 '김정임 상세정보.xls',
 '김정호 상세정보.xls',
 '김조국 상세정보.xls',
 '김중린 상세정보.xls',
 '김중협 상세정보.xls',
 '김지선 상세정보.xls',
 '김진범 상세정보.xls',
 '김창광 상세정보.xls',
 '김창남 상세정보.xls',
 '김창도 상세정보.xls',
 '김창룡 상세정보.xls',
 '김창민 상세정보.xls',
 '김창선 상세정보.xls',
 '김창섭 상세정보.xls',
 '김창수 상세정보.xls',
 '김창식 상세정보.xls',
 '김창엽 상세정보.xls',
 '김천균 상세정보.xls',
 '김천길 상세정보.xls',
 '김철 상세정보.xls',
 '김철규 상세정보.xls',
 '김철만 상세정보.xls',
 '김철삼 상세정보.xls',
 '김철수 상세정보.xls',
 '김춘섭 상세정보.xls',
 '김충걸 상세정보.xls',
 '김충성 상세정보.xls',
 '김충일 상세정보.xls',
 '김태봉 상세정보.xls',
 '김태종 상세정보.xls',
 '김평일 상세정보.xls',
 '김평해 상세정보.xls',
 '김풍기 상세정보.xls',
 '김혁철 상세정보.xls',
 '김현주 상세정보.xls',
 '김형룡 상세정보.xls',
 '김형식a 상세정보.xls',
 '김형식b 상세정보.xls',
 '김형준 상세정보.xls',
 '김호철 상세정보.xls',
 '김희숙 상세정보.xls',
 '김희영 상세정보.xls',
 '김히택 상세정보.xls',
 '노광철 상세정보.xls',
 '동정호 상세정보.xls',
 '라동희 상세정보.xls',
 '량만길 상세정보.xls',
 '량원호 상세정보.xls',
 '량정훈 상세정보.xls',
 '려춘석 상세정보.xls',
 '렴철성 상세정보.xls',
 '렴철수 상세정보.xls',
 '로두철 상세정보.xls',
 '로배권 상세정보.xls',
 '로성실 상세정보.xls',
 '류미영 상세정보.xls',
 '류영선 상세정보.xls',
 '류영섭 상세정보.xls',
 '류현식 상세정보.xls',
 '리강선 상세정보.xls',
 '리경식 상세정보.xls',
 '리경철 상세정보.xls',
 '리광곤 상세정보.xls',
 '리광근 상세정보.xls',
 '리광철 상세정보.xls',
 '리광호 상세정보.xls',
 '리국철 상세정보.xls',
 '리근 상세정보.xls',
 '리길성 상세정보.xls',
 '리길송 상세정보.xls',
 '리길춘 상세정보.xls',
 '리동호 상세정보.xls',
 '리두성 상세정보.xls',
 '리득남 상세정보.xls',
 '리룡남 상세정보.xls',
 '리룡하 상세정보.xls',
 '리만건 상세정보.xls',
 '리명길 상세정보.xls',
 '리명산 상세정보.xls',
 '리명수 상세정보.xls',
 '리무영 상세정보.xls',
 '리병삼 상세정보.xls',
 '리병철 상세정보.xls',
 '리봉죽 상세정보.xls',
 '리설주 상세정보.xls',
 '리성국a 상세정보.xls',
 '리성국b 상세정보.xls',
 '리성학 상세정보.xls',
 '리성호 상세정보.xls',
 '리수용 상세정보.xls',
 '리승호 상세정보.xls',
 '리영길 상세정보.xls',
 '리영래 상세정보.xls',
 '리영수 상세정보.xls',
 '리영용 상세정보.xls',
 '리영익 상세정보.xls',
 '리영호 상세정보.xls',
 '리용무 상세정보.xls',
 '리용선 상세정보.xls',
 '리용주 상세정보.xls',
 '리용철a 상세정보.xls',
 '리용철b 상세정보.xls',
 '리용호 상세정보.xls',
 '리원일 상세정보.xls',
 '리을설 상세정보.xls',
 '리일환 상세정보.xls',
 '리자방 상세정보.xls',
 '리재남 상세정보.xls',
 '리재일 상세정보.xls',
 '리정남 상세정보.xls',
 '리제강 상세정보.xls',
 '리제선 상세정보.xls',
 '리종국 상세정보.xls',
 '리종무 상세정보.xls',
 '리종산 상세정보.xls',
 '리종식 상세정보.xls',
 '리종옥 상세정보.xls',
 '리종혁 상세정보.xls',
 '리주오 상세정보.xls',
 '리찬복 상세정보.xls',
 '리철만 상세정보.xls',
 '리철산 상세정보.xls',
 '리철진 상세정보.xls',
 '리춘삼 상세정보.xls',
 '리충길 상세정보.xls',
 '리태남 상세정보.xls',
 '리태섭 상세정보.xls',
 '리태일 상세정보.xls',
 '리태철 상세정보.xls',
 '리택건 상세정보.xls',
 '리하일 상세정보.xls',
 '리학철 상세정보.xls',
 '리혁권 상세정보.xls',
 '리현 상세정보.xls',
 '리형근 상세정보.xls',
 '리혜정 상세정보.xls',
 '리호림 상세정보.xls',
 '리히용 상세정보.xls',
 '림경만 상세정보.xls',
 '림광일 상세정보.xls',
 '림남수 상세정보.xls',
 '림동옥 상세정보.xls',
 '림상종 상세정보.xls',
 '림준길 상세정보.xls',
 '마원춘 상세정보.xls',
 '마종선 상세정보.xls',
 '맹경일 상세정보.xls',
 '문경덕 상세정보.xls',
 '문명학 상세정보.xls',
 '문응조 상세정보.xls',
 '문재덕 상세정보.xls',
 '문재철 상세정보.xls',
 '문철 상세정보.xls',
 '박경삼 상세정보.xls',
 '박경선 상세정보.xls',
 '박경철 상세정보.xls',
 '박관오 상세정보.xls',
 '박광식 상세정보.xls',
 '박광웅 상세정보.xls',
 '박광호 상세정보.xls',
 '박금희 상세정보.xls',
 '박기서 상세정보.xls',
 '박길연 상세정보.xls',
 '박도춘 상세정보.xls',
 '박림수 상세정보.xls',
 '박만호 상세정보.xls',
 '박명국 상세정보.xls',
 '박명선 상세정보.xls',
 '박명순 상세정보.xls',
 '박명철a 상세정보.xls',
 '박명철b 상세정보.xls',
 '박봉주 상세정보.xls',
 '박성철a 상세정보.xls',
 '박성철b 상세정보.xls',
 '박송남 상세정보.xls',
 '박송봉 상세정보.xls',
 '박수길 상세정보.xls',
 '박수일 상세정보.xls',
 '박순희 상세정보.xls',
 '박승원 상세정보.xls',
 '박영식 상세정보.xls',
 '박영호 상세정보.xls',
 '박용석 상세정보.xls',
 '박용일 상세정보.xls',
 '박용팔 상세정보.xls',
 '박의춘 상세정보.xls',
 '박인철 상세정보.xls',
 '박재경 상세정보.xls',
 '박정근 상세정보.xls',
 '박정남 상세정보.xls',
 '박정순 상세정보.xls',
 '박정천 상세정보.xls',
 '박지민 상세정보.xls',
 '박진식 상세정보.xls',
 '박창호 상세정보.xls',
 '박철민 상세정보.xls',
 '박춘남 상세정보.xls',
 '박태덕 상세정보.xls',
 '박태성 상세정보.xls',
 '박태원 상세정보.xls',
 '박태화 상세정보.xls',
 '박혁철 상세정보.xls',
 '박형렬 상세정보.xls',
 '박호영 상세정보.xls',
 '박훈 상세정보.xls',
 '방강수 상세정보.xls',
 '배달준 상세정보.xls',
 '백계룡 상세정보.xls',
 '백남순 상세정보.xls',
 '백룡천 상세정보.xls',
 '백세봉 상세정보.xls',
 '백용호 상세정보.xls',
 '백인준 상세정보.xls',
 '백학림 상세정보.xls',
 '변영립 상세정보.xls',
 '변인선 상세정보.xls',
 '서종진 상세정보.xls',
 '서창룡 상세정보.xls',
 '서호원 상세정보.xls',
 '서홍찬 상세정보.xls',
 '성자립 상세정보.xls',
 '손광호 상세정보.xls',
 '손영훈 상세정보.xls',
 '손철주 상세정보.xls',
 '송승철 상세정보.xls',
 '송일호 상세정보.xls',
 '송춘섭 상세정보.xls',
 '송호경 상세정보.xls',
 '승정규 상세정보.xls',
 '신룡만 상세정보.xls',
 '신만균 상세정보.xls',
 '신병철 상세정보.xls',
 '신선호 상세정보.xls',
 '신영철 상세정보.xls',
 '신창일 상세정보.xls',
 '심국룡 상세정보.xls',
 '심상진 상세정보.xls',
 '심영학 상세정보.xls',
 '심철호 상세정보.xls',
 '안경호 상세정보.xls',
 '안극태 상세정보.xls',
 '안금철 상세정보.xls',
 '안동춘 상세정보.xls',
 '안정수 상세정보.xls',
 '안지용 상세정보.xls',
 '양승호 상세정보.xls',
 '양형섭 상세정보.xls',
 '엄정철 상세정보.xls',
 '여원구 상세정보.xls',
 '연형묵 상세정보.xls',
 '오경룡 상세정보.xls',
 '오경석 상세정보.xls',
 '오극렬 상세정보.xls',
 '오금철 상세정보.xls',
 '오동일 상세정보.xls',
 '오수용 상세정보.xls',
 '오응창 상세정보.xls',
 '오일정 상세정보.xls',
 '오진우 상세정보.xls',
 '오춘복 상세정보.xls',
 '왕창욱 상세정보.xls',
 '우동측 상세정보.xls',
 '우상철 상세정보.xls',
 '원길우 상세정보.xls',
 '원도희 상세정보.xls',
 '원동연 상세정보.xls',
 '원응희 상세정보.xls',
 '위성일 상세정보.xls',
 '유진 상세정보.xls',
 '유철우 상세정보.xls',
 '윤기정 상세정보.xls',
 '윤동현 상세정보.xls',
 '윤영식 상세정보.xls',
 '윤정린 상세정보.xls',
 '윤정호 상세정보.xls',
 '이동석 상세정보.xls',
 '임경재 상세정보.xls',
 '임철웅 상세정보.xls',
 '임출웅 상세정보.xls',
 '임훈 상세정보.xls',
 '자성남 상세정보.xls',
 '장경일 상세정보.xls',
 '장광봉 상세정보.xls',
 '장금철 상세정보.xls',
 '장기호 상세정보.xls',
 '장길룡 상세정보.xls',
 '장길성 상세정보.xls',
 '장병규 상세정보.xls',
 '장성길 상세정보.xls',
 '장성우 상세정보.xls',
 '장성택 상세정보.xls',
 '장세철 상세정보.xls',
 '장영록 상세정보.xls',
 '장웅 상세정보.xls',
 '장윤곤 상세정보.xls',
 '장재언 상세정보.xls',
 '장정남 상세정보.xls',
 '장정애 상세정보.xls',
 '장정주 상세정보.xls',
 '장준상 상세정보.xls',
 '장창하 상세정보.xls',
 '장철 상세정보.xls',
 '장춘성 상세정보.xls',
 '장춘실 상세정보.xls',
 '장혁 상세정보.xls',
 '장혜명 상세정보.xls',
 '전경남 상세정보.xls',
 '전광호 상세정보.xls',
 '전길수 상세정보.xls',
 '전병호 상세정보.xls',
 '전승훈 상세정보.xls',
 '전영진 상세정보.xls',
 '전용남 상세정보.xls',
 '전일춘 상세정보.xls',
 '전일호 상세정보.xls',
 '전종수 상세정보.xls',
 '전창복 상세정보.xls',
 '전태수 상세정보.xls',
 '전하철 상세정보.xls',
 '전학철 상세정보.xls',
 '전현철 상세정보.xls',
 '전희정 상세정보.xls',
 '정경택 상세정보.xls',
 '정덕기 상세정보.xls',
 '정명도 상세정보.xls',
 '정명학 상세정보.xls',
 '정봉석 상세정보.xls',
 '정상학 상세정보.xls',
 '정승일 상세정보.xls',
 '정연과 상세정보.xls',
 '정영국 상세정보.xls',
 '정영수 상세정보.xls',
 '정영원 상세정보.xls',
 '정인철 상세정보.xls',
 '정태양 상세정보.xls',
 '정호균 상세정보.xls',
 '조경철 상세정보.xls',
 '조남진 상세정보.xls',
 '조명록 상세정보.xls',
 '조병주 상세정보.xls',
 '조석호 상세정보.xls',
 '조연준 상세정보.xls',
 '조영철 상세정보.xls',
 '조용원 상세정보.xls',
 '조정호 상세정보.xls',
 '조춘룡 상세정보.xls',
 '조현주 상세정보.xls',
 '조혜숙 상세정보.xls',
 '주규창 상세정보.xls',
 '주동찬 상세정보.xls',
 '주상성 상세정보.xls',
 '주영길 상세정보.xls',
 '주영식 상세정보.xls',
 '주용일 상세정보.xls',
 '주진구 상세정보.xls',
 '주창일 상세정보.xls',
 '주철규 상세정보.xls',
 '지재룡 상세정보.xls',
 '진금송 상세정보.xls',
 '차명남 상세정보.xls',
 '차선모 상세정보.xls',
 '차승수 상세정보.xls',
 '차희림 상세정보.xls',
 '채성학 상세정보.xls',
 '채일룡 상세정보.xls',
 '채희정 상세정보.xls',
 '최강 상세정보.xls',
 '최강일 상세정보.xls',
 '최경성 상세정보.xls',
 '최경철 상세정보.xls',
 '최광 상세정보.xls',
 '최광래 상세정보.xls',
 '최광진 상세정보.xls',
 '최권수 상세정보.xls',
 '최기룡 상세정보.xls',
 '최동명 상세정보.xls',
 '최룡해 상세정보.xls',
 '최명철 상세정보.xls',
 '최배진 상세정보.xls',
 '최부일 상세정보.xls',
 '최상건 상세정보.xls',
 '최상려 상세정보.xls',
 '최선희 상세정보.xls',
 '최성근 상세정보.xls',
 '최성익 상세정보.xls',
 '최수헌 상세정보.xls',
 '최승호 상세정보.xls',
 '최영건 상세정보.xls',
 '최영림 상세정보.xls',
 '최영일 상세정보.xls',
 '최영호a 상세정보.xls',
 '최영호b 상세정보.xls',
 '최익규 상세정보.xls',
 '최인덕 상세정보.xls',
 '최일룡 상세정보.xls',
 '최정룡 상세정보.xls',
 '최종건 상세정보.xls',
 '최진수 상세정보.xls',
 '최창식 상세정보.xls',
 '최춘식 상세정보.xls',
 '최칠남 상세정보.xls',
 '최태복 상세정보.xls',
 '최휘 상세정보.xls',
 '최희정 상세정보.xls',
 '최희태 상세정보.xls',
 '태종수 상세정보.xls',
 '태형철 상세정보.xls',
 '포희성 상세정보.xls',
 '한광복 상세정보.xls',
 '한광상 상세정보.xls',
 '한동근 상세정보.xls',
 '한룡국 상세정보.xls',
 '한상준 상세정보.xls',
 '한성렬 상세정보.xls',
 '한성룡 상세정보.xls',
 '한종혁 상세정보.xls',
 '한호성 상세정보.xls',
 '한효연 상세정보.xls',
 '한흥표 상세정보.xls',
 '허광욱 상세정보.xls',
 '허영률 상세정보.xls',
 '허종 상세정보.xls',
 '허종호 상세정보.xls',
 '허철만 상세정보.xls',
 '허택 상세정보.xls',
 '현상주 상세정보.xls',
 '현송월 상세정보.xls',
 '현영철 상세정보.xls',
 '현철해 상세정보.xls',
 '홍광순 상세정보.xls',
 '홍서헌 상세정보.xls',
 '홍석형 상세정보.xls',
 '홍선옥 상세정보.xls',
 '홍성남 상세정보.xls',
 '홍승무 상세정보.xls',
 '홍영칠 상세정보.xls',
 '홍인범 상세정보.xls',
 '홍일천 상세정보.xls',
 '황민 상세정보.xls',
 '황병서 상세정보.xls',
 '황봉영 상세정보.xls',
 '황순희 상세정보.xls',
 '황철식 상세정보.xls',
 '황학원 상세정보.xls']

In [13]:
nkfolder=pd.DataFrame(fn,columns=['fname'])

In [15]:
nkfolder

            fname
0    강관주 상세정보.xls
1    강능수 상세정보.xls
2    강동윤 상세정보.xls
3    강련학 상세정보.xls
4    강명철 상세정보.xls
..            ...
596  황병서 상세정보.xls
597  황봉영 상세정보.xls
598  황순희 상세정보.xls
599  황철식 상세정보.xls
600  황학원 상세정보.xls

[601 rows x 1 columns]

In [16]:
nkfolder["ID"]=""
nkfolder

            fname ID
0    강관주 상세정보.xls
1    강능수 상세정보.xls
2    강동윤 상세정보.xls
3    강련학 상세정보.xls
4    강명철 상세정보.xls
..            ... ..
596  황병서 상세정보.xls
597  황봉영 상세정보.xls
598  황순희 상세정보.xls
599  황철식 상세정보.xls
600  황학원 상세정보.xls

[601 rows x 2 columns]

In [17]:
nkfolder.fname.str.split(" ").str[0]

0      강관주
1      강능수
2      강동윤
3      강련학
4      강명철
      ...
596    황병서
597    황봉영
598    황순희
599    황철식
600    황학원
Name: fname, Length: 601, dtype: object

In [18]:
nkfolder.ID = nkfolder.fname.str.split(" ").str[0]

In [19]:
nkfolder

            fname   ID
0    강관주 상세정보.xls  강관주
1    강능수 상세정보.xls  강능수
2    강동윤 상세정보.xls  강동윤
3    강련학 상세정보.xls  강련학
4    강명철 상세정보.xls  강명철
..            ...  ...
596  황병서 상세정보.xls  황병서
597  황봉영 상세정보.xls  황봉영
598  황순희 상세정보.xls  황순희
599  황철식 상세정보.xls  황철식
600  황학원 상세정보.xls  황학원

[601 rows x 2 columns]

In [20]:
nkmerge=nklist.merge(nkfolder,on="ID",how="outer")

In [21]:
nkmerge

,ID,Name,성명(한글),소속/직책,성별,생년월일,출생지,사망여부,사망일자,fname
0,강관주,강관주,NaN,NaN,남성,1930년 07월 05일,평안남도 대동군,NaN,연도미상,강관주 상세정보.xls
1,강능수,강능수,NaN,(사망) 당 중앙위원회 위원,남성,1930년 02월 21일,평양시,(사망),2015년 07월 01일,강능수 상세정보.xls
2,강동윤,강동윤,NaN,당 중앙위원회 부부장,남성,연도미상,NaN,NaN,연도미상,강동윤 상세정보.xls
3,강련학,강련학,강연학,(사망) 민족화해협의회 부회장,남성,연도미상,NaN,(사망),2016년 10월 01일,강련학 상세정보.xls
4,강명철,강명철,NaN,조선그리스도교연맹 중앙위원회 위원장,남성,연도미상,NaN,NaN,연도미상,강명철 상세정보.xls
...,...,...,...,...,...,...,...,...,...,...
600,황병서,황병서,NaN,인민군 차수,남성,1949년,NaN,NaN,연도미상,황병서 상세정보.xls
601,황봉영,황봉영,NaN,조선올림픽위원회 부위원장,남성,1944년 08월 15일,NaN,NaN,연도미상,황봉영 상세정보.xls
602,황순희,황순희,NaN,(사망) 조선혁명박물관 관장,여성,1919년 05월 03일,북한지역외 중국,(사망),2020년 01월 17일,황순희 상세정보.xls
603,황철식,황철식,NaN,NaN,미상,연도미상,NaN,NaN,연도미상,황철식 상세정보.xls
604,황학원,황학원,NaN,NaN,남성,1941년 01월 01일,NaN,NaN,연도미상,황학원 상세정보.xls

In [22]:
# check for items in folder, not in checklist
nkmerge[nkmerge["Name"].isnull()]

Empty DataFrame
Columns: [ID, Name, 성명(한글), 소속/직책, 성별, 생년월일, 출생지, 사망여부, 사망일자, fname]
Index: []

In [23]:
# check for items in checklist, not in folder
nkmerge[nkmerge["fname"].isnull()]

      ID Name 성명(한글)            소속/직책  성별   생년월일  출생지 사망여부  사망일자 fname
241  리상관  리상관    이상관              NaN  남성   연도미상  NaN  NaN  연도미상   NaN
242  리상원  리상원    이상원  최고인민회의 제14기 대의원  남성  1951년  NaN  NaN  연도미상   NaN
243  리선권  리선권    NaN            외무성 상  남성   연도미상  NaN  NaN  연도미상   NaN
482  정경일  정경일    NaN              NaN  미상   연도미상  NaN  NaN  연도미상   NaN

In [24]:
nkmerge[nkmerge["fname"].notnull() & nkmerge["Name"].notnull()]

,ID,Name,성명(한글),소속/직책,성별,생년월일,출생지,사망여부,사망일자,fname
0,강관주,강관주,NaN,NaN,남성,1930년 07월 05일,평안남도 대동군,NaN,연도미상,강관주 상세정보.xls
1,강능수,강능수,NaN,(사망) 당 중앙위원회 위원,남성,1930년 02월 21일,평양시,(사망),2015년 07월 01일,강능수 상세정보.xls
2,강동윤,강동윤,NaN,당 중앙위원회 부부장,남성,연도미상,NaN,NaN,연도미상,강동윤 상세정보.xls
3,강련학,강련학,강연학,(사망) 민족화해협의회 부회장,남성,연도미상,NaN,(사망),2016년 10월 01일,강련학 상세정보.xls
4,강명철,강명철,NaN,조선그리스도교연맹 중앙위원회 위원장,남성,연도미상,NaN,NaN,연도미상,강명철 상세정보.xls
...,...,...,...,...,...,...,...,...,...,...
600,황병서,황병서,NaN,인민군 차수,남성,1949년,NaN,NaN,연도미상,황병서 상세정보.xls
601,황봉영,황봉영,NaN,조선올림픽위원회 부위원장,남성,1944년 08월 15일,NaN,NaN,연도미상,황봉영 상세정보.xls
602,황순희,황순희,NaN,(사망) 조선혁명박물관 관장,여성,1919년 05월 03일,북한지역외 중국,(사망),2020년 01월 17일,황순희 상세정보.xls
603,황철식,황철식,NaN,NaN,미상,연도미상,NaN,NaN,연도미상,황철식 상세정보.xls
604,황학원,황학원,NaN,NaN,남성,1941년 01월 01일,NaN,NaN,연도미상,황학원 상세정보.xls

In [25]:
nkmerge[nkmerge["Name"].str.match("리상관")]

      ID Name 성명(한글) 소속/직책  성별  생년월일  출생지 사망여부  사망일자 fname
241  리상관  리상관    이상관   NaN  남성  연도미상  NaN  NaN  연도미상   NaN

In [26]:
nkmerge[nkmerge["Name"].str.match("리상원")]

      ID Name 성명(한글)            소속/직책  성별   생년월일  출생지 사망여부  사망일자 fname
242  리상원  리상원    이상원  최고인민회의 제14기 대의원  남성  1951년  NaN  NaN  연도미상   NaN

In [27]:
nkmerge[nkmerge["Name"].str.match("리선권")]

      ID Name 성명(한글)  소속/직책  성별  생년월일  출생지 사망여부  사망일자 fname
243  리선권  리선권    NaN  외무성 상  남성  연도미상  NaN  NaN  연도미상   NaN

In [28]:
nkmerge[nkmerge["Name"].str.match("정경일")]

      ID Name 성명(한글) 소속/직책  성별  생년월일  출생지 사망여부  사망일자 fname
482  정경일  정경일    NaN   NaN  미상  연도미상  NaN  NaN  연도미상   NaN